buildscript {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
    dependencies {
        // 版本号必须和 media 目录使用的 Kotlin 版本保持一致
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.0.20"
    }
}
plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.chaquo.python apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

project(':app').tasks.matching { it.name ==~ /assemble.+Release/ }.configureEach {
    doLast {
        copy {
            from fileTree("$rootDir/app/build/outputs/apk") { include '**/release/*.apk' }
            into "$rootDir/Release/apk"
            eachFile { it.path = it.name }
            includeEmptyDirs = false
        }
    }
}
